src/github.com/cab105/terraform-provider-exoscale/exoscale/compute_resource.go
Keypain does not seems to be what should be written here ;)
=> Fix typo: keypain -> keypair

Makefile, src/github.com/exoscale/terraform-provider-exoscale/exoscale/affinity_resource.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/client.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/compute_resource.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/dns_resource.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/security_group_resource.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/ssh_resource.go
redo of #21 which has merge conflicts.
Fixes #21
=> project: update egoscale path following relocation

src/github.com/exoscale/terraform-provider-exoscale/exoscale/affinity_resource.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/compute_resource.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/dns_resource.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/s3bucket_resource.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/s3object_resource.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/security_group_resource.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/ssh_resource.go
=> Removing deprecated id field from schema

.travis.yml, Makefile, README.md, src/github.com/exoscale/terraform-provider-exoscale/exoscale/affinity_resource.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/client.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/compute_resource.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/dns_resource.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/provider.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/s3bucket_resource.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/s3object_resource.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/s3utils.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/security_group_resource.go, src/github.com/exoscale/terraform-provider-exoscale/exoscale/ssh_resource.go
Enabling the travis build to double check that `gofmt` was properly done.
=> gofmt + travis

Makefile, README.md, examples/cloud-init/README.md, examples/cloud-init/data.tf, examples/cloud-init/init.tpl, examples/cloud-init/instances.tf, examples/cloud-init/variables.tf, exoscale/compute_resource.go, exoscale/ip_resource.go, exoscale/nic_resource.go, exoscale/secondaryip_resource.go
Creating a proper cloudinit config file, is a bit harder that previously advertised but much more powerful now.
https://www.terraform.io/docs/providers/template/d/cloudinit_config.html
requires: https://github.com/exoscale/egoscale/pull/36
=> example: using proper cloudinit setup

exoscale/compute_resource.go
=> compute: fix null pointer exception

Gopkg.lock, Gopkg.toml, examples/cloud-init/data.tf, exoscale/compute_resource.go
Attempt to avoid issue reported by @olmoser #59 (aka the examples are broken)
(Closes #59)
=> compute: encode unencoded cloud-init config

README.md, examples/import-compute/.gitignore, exoscale/compute_resource.go, exoscale/secondaryip_resource.go
importing a compute should also imports the linked elastic ip's linked to it.
=> compute: import elastic ips

Gopkg.lock, Gopkg.toml, exoscale/compute_resource.go, exoscale/network_resource.go, exoscale/nic_resource.go
You may `deploy` a stopped VM.
Requires: https://github.com/exoscale/egoscale/pull/51
=> compute: enable deploying a stopped VM

README.md, exoscale/domain_record_resource.go
=> record: add hostname attribute

exoscale/ip_resource.go
=> ip: handle missing resource

Gopkg.lock, Gopkg.toml, exoscale/affinity_resource.go, exoscale/client.go, exoscale/compute_resource.go, exoscale/ip_resource.go, exoscale/network_resource.go, exoscale/nic_resource.go, exoscale/provider.go, exoscale/secondaryip_resource.go, exoscale/security_group_resource.go, exoscale/security_group_rule_resource.go, exoscale/tags.go
Requires https://github.com/exoscale/egoscale/pull/44
=> global: unify all async calls

exoscale/compute_resource.go, exoscale/security_group_resource.go
Ref. #70, Requires https://github.com/exoscale/egoscale/pull/53
Better errors, when you try to mix id and name for both affinity or security groups.
```hcl
security_group_ids = ["${exoscale_security_group.default.name}"]
```
> * exoscale_compute.ada: API error 431 (internal code: 9999): Unable to execute API command deployvirtualmachine due to invalid value. Invalid parameter securitygroupids value=default due to incorrect long value format, or entity does not exist or due to incorrect parameter annotation for the field in api cmd class.
```hcl
security_groups = ["${exoscale_security_group.default.id}"]
```
> * exoscale_compute.ada: API error 431 (internal code: 4350): Unable to find group by name 21a14a60-be48-4bde-8509-ae6ed0231ed0
And a better output.
```
$ terraform show …
```
=> compute: separate groups' name and id

Gopkg.lock, Gopkg.toml, README.md, examples/import-compute/instances.tf, exoscale/affinity_resource.go, exoscale/client.go, exoscale/compute_resource.go, exoscale/ip_resource.go, exoscale/network_resource.go, exoscale/nic_resource.go, exoscale/provider.go, exoscale/secondaryip_resource.go, exoscale/security_group_resource.go, exoscale/security_group_rule_resource.go, exoscale/ssh_resource.go
No more calls are made without a Context.
=> add timeouts everywhere

exoscale/affinity_resource.go, exoscale/client.go, exoscale/compute_resource.go, exoscale/provider.go, exoscale/security_group_resource.go, exoscale/security_group_rule_resource.go, exoscale/ssh_resource.go
Requires https://github.com/exoscale/egoscale/pull/52
=> compute: rely on generic get

Gopkg.lock, Gopkg.toml
- terraform -> 0.11.4
- go-ini -> 1.33.0
=> dep: upgrade terraform, go-ini

exoscale/compute_resource.go
when you spawn a new VM, the password will be kept. E.g.
```
exoscale_compute.vm:
id = 46c2eed6-2b22-487a-be16-8c879aafaa65
ip_address = 185.150.8.20
password = pK5bmp
username = ubuntu
```
=> compute: expose username and password

Gopkg.lock, Gopkg.toml, exoscale/affinity_resource.go, exoscale/compute_resource.go, exoscale/ip_resource.go, exoscale/network_resource.go, exoscale/secondaryip_resource.go, exoscale/security_group_resource.go, exoscale/ssh_resource.go
use master terraform version, for https://github.com/hashicorp/terraform/issues/17672
also, less code with `ImportStatePassthrough`
=> Nil timeouts

exoscale/compute_resource.go
Closes #100 
The behavior regarding ip4 was also strange when the machine started in a `Stopped` state. `ip4` was set to `false`.
=> compute: state wasn't correct

Gopkg.lock, Gopkg.toml, exoscale/compute_resource.go
=> compute: adapt to recent deprecations

exoscale/compute_resource.go
=> compute: fix ip6 was ""

examples/README.md, examples/import-compute/config.tf, examples/ipv6/main.tf, examples/multipart-cloud-init/.gitignore, examples/multipart-cloud-init/README.md, examples/multipart-cloud-init/cloud-init.yml.tpl, examples/multipart-cloud-init/data.tf, examples/multipart-cloud-init/instances.tf, examples/multipart-cloud-init/main.tf, examples/multipart-cloud-init/outputs.tf, examples/multipart-cloud-init/terraform.tfvars.example, examples/multipart-cloud-init/variables.tf
=> Multi part cloud-init

Gopkg.lock, Gopkg.toml
to be tested...
- https://github.com/exoscale/egoscale/pull/66
=> dep: update terraform, egoscale

exoscale/compute_resource.go
=> compute: pick username from template Details

.travis.yml, Gopkg.lock, Makefile, exoscale/affinity_resource_test.go, exoscale/client.go, exoscale/compute_resource_test.go, exoscale/ip_resource.go, exoscale/ip_resource_test.go, exoscale/provider_test.go, exoscale/security_group_resource_test.go, exoscale/ssh_resource_test.go
=> provider: basic test

.travis.yml, Gopkg.lock, Gopkg.toml, exoscale/compute_resource_test.go
=> deps: upgrade egoscale

Gopkg.lock, Gopkg.toml, exoscale/compute_resource.go, website/docs/r/compute.html.markdown
Add the ability to import/read the user data from an instance.
=> Import user data

Gopkg.lock, exoscale/security_group_rule_resource.go, website/docs/r/security_group_rule.html.markdown
```
$ cs authorizeSecurityGroupIngress \
--securitygroupid=4bfe1073-a6d4-48bd-8f24-2ab586674092  \
--cidrlist ::/0
```
```json
{
"account": "yoan.blanc@exoscale.ch",
"description": "dummy (for test)",
"domain": "yoan.blanc@exoscale.ch",
"domainid": "2da0d0d3-e7b2-42ef-805d-eb2ea90ae7ef",
"id": "4bfe1073-a6d4-48bd-8f24-2ab586674092",
"ingressrule": [
{
"cidr": "::/0",
"protocol": "all",
"ruleid": "46d95c89-0ced-4799-b745-e42b45a40b39"
}
],
"name": "wide-open"
}
```
=> ```security group rule: allow ALL

exoscale/domain_resource.go, exoscale/domain_resource_test.go
**NB** testing the domain record as it requires an existing domain to be there... unless I find a solution
=> tests: add acceptance test for DNS domain

.goreleaser.yml, Makefile
goreleaser ftw
```
build
├── config.yaml
├── darwin_amd64
│   └── terraform-provider-exoscale_v0.9.22-1325575
├── linux_amd64
│   └── terraform-provider-exoscale_v0.9.22-1325575
├── terraform-provider-exoscale_SNAPSHOT-1325575_checksums.txt
├── terraform-provider-exoscale_SNAPSHOT-1325575_checksums.txt.asc
├── terraform-provider-exoscale_SNAPSHOT-1325575_darwin_amd64.tar.gz
├── terraform-provider-exoscale_SNAPSHOT-1325575_darwin_amd64.tar.gz.asc
├── terraform-provider-exoscale_SNAPSHOT-1325575_linux_amd64.tar.gz
├── terraform-provider-exoscale_SNAPSHOT-1325575_linux_amd64.tar.gz.asc
├── terraform-provider-exoscale_SNAPSHOT-1325575_windows_amd64.tar.gz
├── terraform-provider-exoscale_SNAPSHOT-1325575_windows_amd64.tar.gz.asc
└── windows_amd64
└── …
```
=> build. use goreleaser

Gopkg.lock, Gopkg.toml
=> deps: upgrade egoscale to 0.9.27

.goreleaser.yml, exoscale/provider.go
=> goreleaser: disable CGO

exoscale/compute_resource.go
=> compute: use Details to activate ipv6

exoscale/resource_domain.go, exoscale/resource_domain_record.go
when used with bad credentials, it could erase the state... Failing during the read should force the user to perform a manual `state rm`
=> domain: try to not erase things

exoscale/resource_exoscale_nic.go
The `listNics` call will return IP addresses associated to nics in
managed private networks even if the IP is not static.
Terraform should only update the IP address associated to a nic if an
IP is set in the Terraform file, and if the IP returned by `listNics`
is different.
=> Nics: Managed private network API change
